### ISSUE TITLE
PoC: Rate limiting

### ISSUE THREAD

**Issue by unleashed** [3scale/ostia#17]
[this is still WIP on the text below]

# Rate Limiting

## Definition

Rate limiting is the act of placing a limit to the number of times a resource is
accessed or consumed per unit of time. The definitions of resource and access
can vary wildly, but they are of no concern to rate limiting.

For our purposes, rate limiting is about defining rules that place limits to the
number of requests that access or consume API resources.

### Examples

These are all examples of rate limiting in the API context:

"The endpoint /big-red-button can be accessed 0 times"
"The endpoint /daily-report can only be accessed once per day"
"The client address 127.0.0.1 can access any endpoint up to 10 times per minute"
"The whole system can at most receive 500 POST requests per second"
"Requests with a specific header can access /secret up to 5 times per minute"

Note that the number of times in which a resource can be consumed is sometimes
attached to the resource and sometimes to the consumer, and potentially could be
attached to both at the same time:

"Id 1 can access resorce A up to 500 times per hour".

### Complexity

In order to honor the limits to the number of requests, the system must count
the requests that each limit cares about. But it is trivial to define rate
limits that overlap or even contradict other rate limits, _further constraining_
access to resources.

For example, while a global rate limit for a service might be set at 10 million
requests per minute, a more specific rate limit based on the client address
might be set at 20 million per hour, and in this case requests might be limited
by just one of the rules.

In the above case there are two different checks that need to pass (ie. not
reach the limit) for a single request. There exists a relation between both, in
which one and the other need to have their counters updated.

The number of counter checks can grow arbitrarily based on the amount of
overlapping properties, and is known as the amplification factor for a given
request given the set of rules for rate limiting.

## 3scale

The definition of rate limiting in 3scale is a limit on a metric, where a metric
is defined as an identifier representing a pattern match on an HTTP request's
path.

The relations between metrics in 3scale are limited to partial pattern matching,
ie. /cars/color might be matching several parts of the path, and so counters
would need to be updated and checked for every match (although 3scale supports
only a limited version of this).

This kind of rate limiting is focused on the resource rather than the consumer.
However the consumer's identity is taken into account to define which limits are
to be applied (although no other property from the consumer is taken into
account, or even from the request in the usual set up).

With more control on the component doing the pattern matching such as the proxy
or the code calling into 3scale, the concept of metric can be redefined to
represent an arbitrary set of rules, such as for example the amount of calls
received on odd seconds, to name just a widly arbitrary rule. However, this is
far from the usual case for 3scale.

## Quotas

A related concept is quotas, which might be defined as credit attached to the
consumer of the resource as opposed to the resource itself. This allows the
consumer to use up their allowance as they wish, possibly setting different
costs to different resources.

For example, your salary limits the amount of goods you can buy, even though
there is no limit to the amount of times a specific good can be bought.

## How would rate limiting work

It seems very likely that a flexible and complete rate limiting feature should
support rate limiting both resources and consumers. To continue with the example
of the previous section, a legitimate use case might be that of someone being
limited on their salary to buy goods and a store having a small amount of goods
to sell. This would require two rules.

If we wanted to provide the best flexibility possible, we'd need to be able to
define rules this way:

### Input

We can match on any information available at request processing time. This can
be anything in the request or the data associated to the consumer.

- Anything related to the consumer
- Anything related to the resource

### Computation

A counter is incremented or decremented and checked against a value (typically
the limit or 0).

### Output

A boolean response stating whether the rate limit accepts the request.

## How would it work in Ostia?

This is one of the main points for discussion. The main issues arising are:

* Scope of what's possible and what's not.
* If willing to go for flexibility, complexity and performance of handling
  multiple limits for each call.
* If willing to go for simplicity, which things do we want to support matching
  and whether we would have chains of rules being considered for limiting.
* Language, configuration, APIs, templating or other means for defining the
  limits covering all the cases we want to cover.

**Comment by andrewdavidmackenzie** [comment]
Some minor comments:
- combining different rules on the same metric at different time granularities can be used to allow for "spikes" or peaks of traffic. e.g. Limit of 60 requests per minute, plus limit of 2 requests per second - allows for a peak during a second, but it cannot continue for more than 30 seconds.
- rate limits could be "wall clock time periods" or moving average. We currently focus more on wall-clock, but could be otherwise.
- sometimes time periods that are not "natural time periods" (minutes, hours) could be useful, we have had requests for limiting over 5seconds for example. Allow arbitrarily defined periods?
- clarify 100% we're not talking throttling or traffic shaping. Requests are accepted or denied immediately.
- inputs section text doesn't match the bullets 100%? could be info related to request, consumer, resource. (Maybe resource owner?....but I don't have good examples) (I think we have seen requests for rate limiting based on a header content - just BTW)
- can rate limit of on other things too, like number of connections open, or number of parallel requests, So maybe on "resources being consumed, or system state or something?
- maybe touch on subject of consistency and different models? Option for total consistency?

**Comment by mikz** [comment]
@unleashed I'd try ty trim it down a bit. It is a lot of text.

@andrewdavidmackenzie Rate Limit policy in APIcast already allows throttling. There is no reason why we should not plan to support that.


To define PoC as minimal implementation here is my take. I tried to design it in a way it is flexible and pluggable, so more conditions and algorithms could be added easily.

# PoC: Rate limiting

## Data model

Rate limits have some properties that could be summarized as: 

* condition (when to apply this limit)
* metric ( name of the counter )
* limit ( rate per in the time window )
* algorithm ( fixed window, token / leaky bucket, sliding window/log ) 
* increment ( value +- )

## Scenarios

Scenarios to verify the data model.

### Scenario 1

Allow for the same client 50 rps when accessing externally but 500 rps when accessing from external network (using the same counter).

Two different limits with different conditions sharing same value.  If client does 40 requests on internal network it can still do 460 from external or 10 from internal.

```yaml
rate_limits:

- name: internal_clients
  conditions:
  - remote_addr:
     match: /^10\.1\.1\./
  metric: "${client_id}_requests"
  limit: 50
  
- conditions:
  - not_match: internal_clients
  metric: "${client_id}_requests"
  limit: 500
```

### Scenario 2

Rate limit GET requests to 50 rps, POST to 500 rps, everything else to combined 100 rps.

This shows how to limit some exceptions differently than others.

```yaml
- name: get_requests
  conditions:
  - http_method: GET
  metric: "http_method:${http_method}"
  limit: 50/s
  
- name: post_requests
  conditions:
  - http_method: POST
  metric: "http_method:${http_method}"
  limit: 500/s
  
- conditions:
  - not_match: get_requests
  - not_match: post_requests
  metric: "http_method:rest"
  limit: 100/s
```

### Scenario 3

Rate limit every IP address to 1000 rps.

How to rate limit by some value from the request into even buckets.

```yaml
- metric: "ip:${remote_addr}"
  limit: 1000/s
```

### Scenario 4

Rate limit identified client to 300 rps.

```yaml
- metric: "client:${client_id}"
  limit: 300s
```

### Scenario 5 

Limit number of opened parallel connections to 100 per IP address.

This shows how to increment / decrement a metric.

```yaml
- metric: "ip:${remote_addr}_connections"
  condition:
    - connection: opened
  limit: 100
  algorithm: leaky_bucket

- metric: "ip:${remote_addr}_connections"
  condition:
    - connection: closed
  increment: -1
  algorithm: leaky_bucket
```


### Scenario 6

Prevent enumeration attacks by rate limiting wildcards in the path.

Shows how to use variables from the condition into the metric name.

```yaml
- conditions:
  - http_path:
      wildcard: "/api/accounts/${account_id}/*"
  metric: "api_accounts_${account_id}_${remote_addr}"
  limit: 10/s
```

**Comment by jmprusi** [comment]
We should try to stick to the initial PoC template, with definition, use cases and goals... :)  

And BTW, after this I think we should talk about CRDs: https://github.com/3scale/ostia/issues/18

**Comment by unleashed** [comment]
We have agreed to split this into two steps.

### Step 1 - Simple rate limiting

The goal of this step is to deploy a very simple rate limiting mechanism using the APIcast rate limiting policy. This should demonstrate a basic mechanism with which we can see that requests to specific endpoints start being denied when the limit is reached.

#### Scenario

I want to limit access to /limited to 1000 requests per minute.

#### Tasks

- [ ] Deploy APIcast with a suitable configuration for its rate limiting policy and check it works correctly

### Step 2 - Conditional rate limiting

Whereas the previous step would have a simple condition to match on a specific endpoint to apply rate limits, this step is a superset which requires support for matching arbitrary conditions based on the data associated to the request, the consumer, the resource, and the environment. This requires APIcast to support a standalone configuration mode in which we are not tied to the 3scale data model, as it limits the matching capabilities.

#### Specification

The way the matching conditions are specified should be defined. The main idea at this stage is to support a configuration with a set of possible static attributes on the different inputs that can be matched, such as a request's path but also the current date or the source address of the consumer. Other ideas, to be developed further down the road, include supporting scripting or a controlled DSL.

#### Scenarios

* "I want to limit the amount of hits to /disco to 100 per minute, but have it be 1000 per minute on weekends"
* "Allow 127.0.0.0/8 and 192.168.0.0/16 addresses only to hit /internal"
* "Limit a specific authenticated user to 100 request per second on /painful, everybody else 10 requests per second, unless it is Christmas, in which not even APIs should work, so that day it should be 0 requests/second for everyone".

 #### Tasks

- [ ] Have APIcast support standalone configuration mode (see 3scale/apicast#795)
- [ ] Define how matching conditions are specified (possibly defined in the standalone config support)
- [ ] Deploy APIcast with a suitable standalone configuration and check it works correctly

## Further steps

One of the main considerations is whether to support a DSL or a programming/scripting language that allows for more flexible matching, as well as (potentially) a way to extend the attributes such a language can take as inputs. istio is known to use a DSL for this. APIcast can always evaluate Lua, but that seems too open and would be dangerous if it was exposed to untrusted parties.

Other options include logic engines (ie. datalog and others), or a DSL designed specifically for this task such that we can sandbox the logic so that a bug or a malicious condition don't exhaust resources.

**Comment by jmprusi** [comment]
I would say, there is more than one task, extending or adding new CRDs to the operator, and making the operator write the correct config...

**Comment by unleashed** [comment]
We can change the current "deploy APIcast" tasks so that it is a bigger group of tasks accomplishing that adding the details about what needs to be done (like the CRDs you mention). Can you think of additional details worth mentioning there? Otherwise I'd say adding/updating CRDs to handle the configuration and deploying and validating.

**Comment by jmprusi** [comment]
To be honest, I would not put a list of tasks, just well defined goals and scenarios :)

Goals can be seen as high level abstract tasks.

**Comment by unleashed** [comment]
There is also a comment in APIcast that made me think about the kind of guarantees that are required for rate limiting.

Specifying the degree of accuracy in rate limiting can be very beneficial for implementations because rate limiting "exactly to N" has performance characteristics wildly different than rate limiting "about N but can tolerate going over limits a bit", and even "about N +/- X hits".

The latter should be ok to protect services without caring too much about the actual limit and is best for performance.

I'll give it a few thoughts and come up with extra scenarios for the steps above (or the further steps section).

**Comment by unleashed** [comment]
From https://github.com/3scale/ostia/issues/17#issuecomment-396913897 scenario 8, I see the motivation is "strict" rate limiting.

I commented before on exposing the threshold of accuracy (aka "strictness") so that implementations can avoid performance issues (latency) caused by needing to sync several nodes on a single source of truth (a counter) that needs to be modified concurrently from several points of access in cases in which full accuracy is not critical.

In those cases full synchronization _can_ be avoided up to a certain threshold. I advocate specifying a value for this concept (and we can talk about what that would look like).

A related concept is soft and hard limits (ie. you could view non-strict limits as "soft" limits and the concept of threshold as defining a "hard" limit), but I am not sure we want to have these concepts here, so that might best be left out for now.

**Comment by mikz** [comment]
@unleashed I think we could achieve the "strictness" by offering a more global way of configuring the "store". Each store will have different characteristics and you could chose which store to use. Not per rate limit, but per a set of rate limits applied together - policy. I think it is not concern of the rate limit itself but more how you apply it.

**Comment by unleashed** [comment]
@mikz I agree about the application to a set of rate limits - but I am not sure about the idea of attaching this concept to a "store" or implementation, since it needs not be an inherent property of that, and some implementations might support both strict limits and relaxed ones with multiple settings. Maybe it simplifies things but it could also cut away some flexibility.

**Comment by mikz** [comment]
Conditional policy just landed in APIcast and already provides some matching operations we can use to  implement some rate limiting PoC: https://github.com/3scale/apicast/pull/814
